### ISSUE TITLE
Refactor add_reviewer function

### ISSUE THREAD

**Issue by salonishah01** [NidhayPancholi/expertiza#2]
Breakdown add_reviewer method into multiple simpler methods

**Comment by salonishah01** [comment]
Refactored the method to do the following:

- Each method now performs a single task, making the code more modular and easier to understand.
- Methods are named descriptively to indicate their purpose.
- Code duplication is reduced by extracting common functionalities into separate methods.
- The main add_reviewer method now orchestrates the process by calling smaller methods for each task.

**Comment by NidhayPancholi** [comment]
The changes for this issue can be checked at - https://github.com/NidhayPancholi/expertiza/commit/b325810d67da2a03d3ccb15458926d0049fdb9eb

Reviewed and closing issue.
